using UnityEngine;
using UnityEngine.Rendering;

namespace MyBird
{
    /// <summary>
    /// 플레이어 캐릭터(Bird)를 관리하는 클래스
    /// 점프, 이동, 충돌
    /// </summary>
    public class Player : MonoBehaviour
    {
        #region Variables
        //참조
        private Rigidbody2D rb2D;

        //대기
        [SerializeField]
        private float readyForce = 5f;

        //점프
        private bool keyJump = false;
        [SerializeField]
        private float jumpForce = 5f;

        //회전
        private Vector3 birdRotation = Vector3.zero;        //회전 값
        [SerializeField]
        private float upRotate = 5f;                        //위로 회전하는 스피드
        [SerializeField]
        private float downRotate = -5f;                     //아내로 회전하는 스피드

        //이동
        [SerializeField]
        private float moveSpeed = 5f;

        //버드 대기 UI
        public GameObject readyUI;

        //게임오버 UI
        public GameObject gameOverUI;

        //사운드
        private AudioSource audioSource;                    //포인트 사운드

        #endregion

        #region Unity Event Method
        private void Start()
        {
            //참조
            rb2D = this.GetComponent<Rigidbody2D>();
            audioSource = this.GetComponent<AudioSource>();

        }

        private void Update()
        {
            //입력 처리
            InputBird();

            //시작 여부 체크
            if (GameManager.IsStart == false)
            {
                return;
            }

            //버드 회전
            RotateBird();

            //버드 이동
            MoveBird();
        }

        private void FixedUpdate()
        {
            //시작 여부 체크
            if (GameManager.IsStart == false)
            {
                //버드 대기
                ReadyBird();

                return;
            }

            //점프하기
            if (keyJump)
            {
                JumpBird();
                keyJump = false;
            }
        }

        //충돌 체크 - 매개변수로 부딪힌 충돌체를 입력 받는다
        private void OnCollisionEnter2D(Collision2D collision)
        {
            //충돌한 충돌체 체크 - 테그로
            if(collision.gameObject.tag == "Ground")
            {
                //Debug.Log("그라운드과 충돌");
                GameManager.IsDeath = true;
                GameOver();
            }
        }

        //매개변수로 부딪힌 충돌체를 입력 받는다
        private void OnTriggerEnter2D(Collider2D collision)
        {
            //충돌한 충돌체 체크 - 테그로
            if(collision.gameObject.tag == "Point")
            {
                GetPoint();
            }
            else if (collision.gameObject.tag == "Pipe")
            {
                //Debug.Log("기둥과 충돌");
                GameManager.IsDeath = true;
                GameOver();
            }

        }

        #endregion

        #region Custom Method
        //점수 획득 처리
        void GetPoint()
        {
            GameManager.Score++;

            //효과 : vfx, sfx
            audioSource.Play();

            //게임 포인트 체크 - 기둥 10개를 통과할 때마다
            if(GameManager.Score % 10 == 0)
            {
                //레벨링
                GameManager.spawnValue += 0.05f;

            }
        }


        //게임 오버 처리
        void GameOver()
        {
            GameManager.IsDeath = true ;
            gameOverUI.SetActive(true);
        }

        //인풋 처리
        void InputBird()
        {
            if (GameManager.IsDeath)
            { return; }

#if UNITY_EDITOR            //유니티 에디터 : 마우스와 키보드 입력 처리
            //스페이스 키 OR 마우스 왼클릭으로 입력받기
            keyJump |= Input.GetKeyDown(KeyCode.Space);
            keyJump |= Input.GetMouseButtonDown(0);
#else                       //그외 플랫폼 : 터치 입력 처리
            if(Input.touchCount > 0)
            {
                //첫번째 들어온 터치 가져오기
                Touch touch = Input.GetTouch(0);

                if(touch.phase == TouchPhase.Began)
                {
                    keyJump |= true;
                }
            }
#endif

            //플레이어 이동 시작
            if(GameManager.IsStart == false && keyJump == true)
            {
                GameManager.IsStart = true;

                //UI
                readyUI.SetActive(false);
            }
        }

        //버드 대기
        void ReadyBird()
        {
            if(rb2D.linearVelocityY < 0f)
            {
                rb2D.linearVelocity = Vector2.up * readyForce;
            }
        }


        //버드 점프하기
        void JumpBird()
        {
            //힘을 이용하여 오브젝트를 위로 이동 => 정확한 값을 넣기 어려움
            //rb2D.AddForce(Vector2.up * jumpForce);

            //rb2D.linearVelocity를 이용하여 오브젝트를 위로 이동
            rb2D.linearVelocity = Vector2.up * jumpForce;

        }

        //버드 회전하기
        void RotateBird()
        {
            //점프해서 올라갈 때 최대 +30도까지 회전
            //내려갈 때 최소 -90도까지 회전

            float degree = 0f;                          //멈춰있을 때

            if(rb2D.linearVelocity.y > 0f)              //올라갈 때
            {
                degree = upRotate;
            }
            else if (rb2D.linearVelocity.y < 0f)        //내려갈 때
            {
                degree = downRotate;
            }

            birdRotation = new Vector3(0f, 0f, Mathf.Clamp(birdRotation.z + degree, -90f, 30f));

            transform.eulerAngles = birdRotation;
        }

        //버드 이동
        void MoveBird()
        {
            if(GameManager.IsDeath)
            { return; }

            transform.Translate(Vector3.right * Time.deltaTime * moveSpeed, Space.World);
        }

#endregion



    }
}
